[package]
name = "goodit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "22.1.0"
actix-web = "4.0.1"
tera = "1.15.0"
serde = "1.0.136"